# Generated by Django 3.1.7 on 2021-04-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210405_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='referral_earnings',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
