# Generated by Django 3.1.7 on 2021-04-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_myusers_referral_earnings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='referral_earnings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
