# Generated by Django 3.1.7 on 2021-04-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
