# Generated by Django 3.1.7 on 2021-04-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0002_categories_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('off', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
